server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_java1234_mall_v3?serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

wexin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wx87ba5ee1edc5756c
  secret: e53e917ddcdf639ba458a628ad49ff2e